export const classNames = {
  CHAT: "_83421f9",
  CHAT_ACTIVE: "b64fb9ae",
  CHAT_TEXT: "c08e6e93",
  CHAT_MAIN_TITLE: "d8ed659a",
  CHAT_INPUT: "ds-input__input",
  CHAT_LIST: "_03210fb",
  CHAT_LIST_EMPTY: "f27d1011",
  SIDEBAR: "dc04ec1d",
  SIDEBAR_CLOSED: "a02af2e6",
  LIST_ROOT: "._03210fb",
  MODAL_DELETE: "ds-button--error",
  CONTEXT_MENU: "ds-floating-position-wrapper",
  RENAME_BTN: "ds-dropdown-menu-option--none",
  DELETE_BTN: "ds-dropdown-menu-option--error",
};
